#!/usr/bin/env bash

source "$OVM_PATH/lib/validator"

local packages=(sed)

__ovm_validator_packages "nft-lr" "${packages[@]}" || return

function nft-lr {
    local x='\x1b[0m'
    local _t='\x1b[1;38;5;6m'
    local _c='\x1b[38;5;207m'
    local _s='\x1b[38;5;217m'
    local _da='\x1b[38;5;112m'
    local _dg='\x1b[38;5;214m'
    local _dr='\x1b[38;5;196m'
    local _p='\x1b[1;38;5;15m'
    local _ct='\x1b[38;5;117m'
    local _ip='\x1b[38;5;75m'
    local _txt='\x1b[38;5;223m'
    local _h='\x1b[38;5;240m'

    local hostname="$1" && shift

    ssh $hostname "nft $@ list ruleset" | sed -E \
        -e "s/^(table\s+)(.+)(\s+\{.*)$/\1${_t}\2${x}\3/" \
        -e "s/^(\s*chain)(.+)(\{.*)$/\1${_c}\2${x}\3/" \
        -e "s/^(\s*set)(.+)(\{.*)$/\1${_s}\2${x}\3/" \
        -e "s/(accept)/${_da}\1${x}/" \
        -e "s/(return|continue)/${_dg}\1${x}/" \
        -e "s/((goto|jump) )([0-9a-zA-Z_-]+)/${_dg}\1${x}${_c}\3${x}/" \
        -e "s#((limit rate) )([0-9a-zA-Z_-]+\/[0-9a-zA-Z_-]+)#${_dg}\1${x}${_c}\3${x}#" \
        -e "s/(reject|drop)/${_dr}\1${x}/" \
        -e "s/(@[0-9a-zA-Z_-]+)/${_s}\1${x}/g" \
        -e "s/(port )((\{ )?[[:digit:], ]+(:[[:digit:]]+)?( \})?)/\1${_p}\2${x}/" \
        -e "s/(port )((\{ )?[[:alpha:], ]+(:[[:alpha:]]+)?( \})?)/\1${_p}\2${x}/" \
        -e "s/(packets|bytes)( [[:digit:]]+)/\1${_ct}\2${x}/g" \
        -e "s/[1-9][[:digit:]]{0,2}\.([[:digit:]]{1,3}\.){2}[[:digit:]]{1,3}(\/([[:digit:]]){1,3}){0,1}/${_ip}&${x}/g" \
        -e "s/(([[:xdigit:]]{1,4}:){7,7}[[:xdigit:]]{1,4}|([[:xdigit:]]{1,4}:){1,7}:|([[:xdigit:]]{1,4}:){1,6}:[[:xdigit:]]{1,4}|([[:xdigit:]]{1,4}:){1,5}(:[[:xdigit:]]{1,4}){1,2}|([[:xdigit:]]{1,4}:){1,4}(:[[:xdigit:]]{1,4}){1,3}|([[:xdigit:]]{1,4}:){1,3}(:[[:xdigit:]]{1,4}){1,4}|([[:xdigit:]]{1,4}:){1,2}(:[[:xdigit:]]{1,4}){1,5}|[[:xdigit:]]{1,4}:((:[[:xdigit:]]{1,4}){1,6})|:((:[[:xdigit:]]{1,4}){1,7}|:)|fe80:(:[[:xdigit:]]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([[:xdigit:]]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))(\/([[:digit:]]){1,3}){0,1}/${_ip}&${x}/g" \
        -e "s/(comment )(".*")/\1${_txt}\2${x}/" \
        -e "s/(# handle.+)$/${_h}\1${x}/" \
    | expand -t2 -
}
