#!/bin/bash

function __ovm_markdown_dumper {
    path=$1

    # Glow: https://github.com/charmbracelet/glow
    glowbin="$GOPATH/bin/glow"
    command -v "$glowbin" >/dev/null 2>&1
    if [ $? -eq 0 ];
    then
        $glowbin -s dark "$path"
        return
    fi
    # Global setup
    command -v glow >/dev/null 2>&1
    if [ $? -eq 0 ];
    then
        glow -s dark "$path"
        return
    fi

    # Pandoc & lynx
    command -v pandoc >/dev/null 2>&1
    if [ $? -eq 0 ];
    then
        command -v lynx >/dev/null 2>&1
        if [ $? -eq 0 ];
        then
            pandoc "$path" | lynx -stdin
            return
        fi
    fi

    # Default
    /bin/cat "$path"
}

function __ovm_highlight {
   declare -A fg_color_map
   fg_color_map[black]=30
   fg_color_map[red]=31
   fg_color_map[green]=32
   fg_color_map[yellow]=33
   fg_color_map[blue]=34
   fg_color_map[magenta]=35
   fg_color_map[cyan]=36

   fg_c=$(echo -e "\e[1;${fg_color_map[$1]}m")
   c_rs=$'\e[0m'
   sed -u s"/$2/$fg_c\0$c_rs/g"
}
