#!/bin/bash

source "$OVM_PATH/lib/validator"

# ---------------------------------------
# Requirements
# ---------------------------------------
local packages=("cat" "curl" "date" "jq" "stat")

__ovm_validator_packages "${packages[@]}" || return

# ---------------------------------------
# Code
# ---------------------------------------
function aws-ipr {
  curl -s -X GET "${OVM_AWS_IPRANGES_URL}" | jq .
}

function aws-ipr-cache {
  target=/tmp/aws-ip-ranges.json

  if [ ! -f "$target" ]; then 
    curl -s -X GET "${OVM_AWS_IPRANGES_URL}" -o "$target"
  else
    created_at=$(stat -c '%W' "$target")
    now=$(date +%s)
    diff=$((($now-$created_at)/60))

    # By default, cache is refreshed if more than 1h
    if [ $diff -ge $OVM_AWS_IPRANGES_CACHE_REFRESH ]; then
      curl -s -X GET "${OVM_AWS_IPRANGES_URL}" -o "$target"
    fi
  fi

  cat "$target" | jq .
}
